export default [
  {
    country: "AT",
    name_worldometers: "Austria",
    name_en: "Austria",
    name_nl: "Oostenrijk",
    lockdown: "yes",
    impact_daily_life: "unkown",
    impact_daily_life_link: "",
    freedom_of_movement: "unkown",
    freedom_of_movement_link: "",
    border_policy: "4. closed some borders and air travel",
    border_policy_link:
      "https://www.aljazeera.com/news/2020/03/coronavirus-travel-restrictions-border-shutdowns-country-200318091505922.html",
    comment_en:
      "Some restaurants still deliver, most are closed. Allowed on the streets only with housemates or while maintaining distance.",
    comment_nl:
      "Sommige restaurants bezorgen maaltijden. Mensen mogen naar buiten als ze afstand bewaren.",
    start: "Mar 16, 2020",
    end: "Mar 23, 2020",
    link:
      "https://www.reuters.com/article/us-health-coronavirus-austria/austrian-province-of-tyrol-on-lockdown-idUSKBN2160WK",
    link2:
      "https://www.sozialministerium.at/Informationen-zum-Coronavirus/Coronavirus---Aktuelle-Ma%C3%9Fnahmen.html",
    new_death_daily_delta_percent: "-71%",
    new_death_daily_delta_absolute: -5
  },
  {
    country: "BE",
    name_worldometers: "Belgium",
    name_en: "Belgium",
    name_nl: "België",
    lockdown: "yes",
    impact_daily_life: "5. all non-essential shops closed",
    impact_daily_life_link: "",
    freedom_of_movement: "3. strong restrictions",
    freedom_of_movement_link: "",
    border_policy: "2. light restrictions",
    border_policy_link: "",
    comment_en: "",
    comment_nl:
      "De grenzen zijn dicht richting Nederland en Frankrijk. Alle zogeheten niet-essentiële verplaatsingen zijn verboden. Alleen Nederlanders die over de grens werken komen er nog in. Er is in België geen sprake van een echte lockdown zoals in Frankrijk of Spanje: Belgen mogen nog gewoon de straat op om een frisse neus te halen. De parken zijn open, wandelaars moeten gepaste afstand tot elkaar bewaren. Wel zijn in tegenstelling tot in Nederland alle niet-essentiële winkels dicht.",
    start: "Mar 18, 2020",
    end: "",
    link: "https://www.belgium.be/en/news/2020/coronavirus_reinforced_measures",
    link2:
      "https://www.belgium.be/nl/nieuws/2020/coronavirus_versterkte_maatregelen",
    new_death_daily_delta_percent: "65%",
    new_death_daily_delta_absolute: 22
  },
  {
    country: "BG",
    name_worldometers: "Bulgaria",
    name_en: "Bulgaria",
    name_nl: "Bulgarije",
    lockdown: "yes",
    impact_daily_life: "4. take away food delivery only",
    impact_daily_life_link: "",
    freedom_of_movement: "3. strong restrictions",
    freedom_of_movement_link: "",
    border_policy: "4. closed some borders and air travel",
    border_policy_link:
      "https://www.aljazeera.com/news/2020/03/coronavirus-travel-restrictions-border-shutdowns-country-200318091505922.html",
    comment_en: "",
    comment_nl: "",
    start: "",
    end: "",
    link:
      "https://www.reuters.com/article/us-health-coronavirus-bulgaria-britain/british-skiers-stuck-in-coronavirus-lockdown-at-bulgaria-resort-idUSKBN2153KN",
    link2: "",
    new_death_daily_delta_percent: "",
    new_death_daily_delta_absolute: ""
  },
  {
    country: "HR",
    name_worldometers: "Croatia",
    name_en: "Croatia",
    name_nl: "Kroatië",
    lockdown: "yes",
    impact_daily_life: "unkown",
    impact_daily_life_link: "",
    freedom_of_movement: "unkown",
    freedom_of_movement_link: "",
    border_policy: "4. closed some borders and air travel",
    border_policy_link:
      "https://www.aljazeera.com/news/2020/03/coronavirus-travel-restrictions-border-shutdowns-country-200318091505922.html",
    comment_en: "",
    comment_nl: "",
    start: "",
    end: "",
    link: "https://www.total-croatia-news.com/news/42223-covid-19",
    link2: "",
    new_death_daily_delta_percent: "",
    new_death_daily_delta_absolute: ""
  },
  {
    country: "CY",
    name_worldometers: "Cyprus",
    name_en: "Cyprus",
    name_nl: "Cyprus",
    lockdown: "yes",
    impact_daily_life: "unkown",
    impact_daily_life_link: "",
    freedom_of_movement: "unkown",
    freedom_of_movement_link: "",
    border_policy: "5. closed all borders and air travel",
    border_policy_link:
      "https://www.aljazeera.com/news/2020/03/coronavirus-travel-restrictions-border-shutdowns-country-200318091505922.html",
    comment_en: "",
    comment_nl: "",
    start: "",
    end: "",
    link:
      "https://www.birminghammail.co.uk/news/world-news/cyprus-radical-plan-prevent-coronavirus-17929840",
    link2: "",
    new_death_daily_delta_percent: "",
    new_death_daily_delta_absolute: ""
  },
  {
    country: "CZ",
    name_worldometers: "Czechia",
    name_en: "Czech Republic",
    name_nl: "Tsjechië",
    lockdown: "yes",
    impact_daily_life: "5. all non-essential shops closed",
    impact_daily_life_link:
      "https://koronavirus.mzcr.cz/en/under-the-declared-state-of-emergency-events-involving-more-than-30-persons-have-been-banned-and-the-presence-of-the-public-in-certain-facilities-has-also-been-restricted/",
    freedom_of_movement: "3. strong restrictions",
    freedom_of_movement_link:
      "https://koronavirus.mzcr.cz/en/the-government-restricts-free-movement-of-people-to-the-necessary-minimum-due-to-the-spread-of-the-coronavirus-epidemic/",
    border_policy: "5. closed all borders and air travel",
    border_policy_link:
      "https://koronavirus.mzcr.cz/en/the-government-restricts-free-movement-of-people-to-the-necessary-minimum-due-to-the-spread-of-the-coronavirus-epidemic/",
    comment_en:
      "Closed borders. Everyone has a face mask outside (police controls that). Lockdown of schools, bars, events and non-essential shops. People are allowed to go to work and do food/drugstore shopping. Take-away food in restaurants only.",
    comment_nl: "",
    start: "Mar 12, 2020",
    end: "",
    link: "https://koronavirus.mzcr.cz/en/",
    link2: "",
    new_death_daily_delta_percent: "0%",
    new_death_daily_delta_absolute: 0
  },
  {
    country: "DK",
    name_worldometers: "Denmark",
    name_en: "Denmark",
    name_nl: "Denemarken",
    lockdown: "mild",
    impact_daily_life: "5. all non-essential shops closed",
    impact_daily_life_link: "",
    freedom_of_movement: "1. no restrictions",
    freedom_of_movement_link: "",
    border_policy: "5. closed all borders and air travel",
    border_policy_link: "",
    comment_en: "Events with more than 10 participants banned",
    comment_nl: "Evenementen met meer dan 10 deelnemers zijn verboden.",
    start: "",
    end: "",
    link:
      "https://politi.dk/en/coronavirus-in-denmark/17-march-2020-new-initiatives-to-prevent-the-spread-of-coronavirus-covid19",
    link2: "",
    new_death_daily_delta_percent: "-75%",
    new_death_daily_delta_absolute: -6
  },
  {
    country: "EE",
    name_worldometers: "Estonia",
    name_en: "Estonia",
    name_nl: "Estland",
    lockdown: "unkown",
    impact_daily_life: "unkown",
    impact_daily_life_link: "",
    freedom_of_movement: "unkown",
    freedom_of_movement_link: "",
    border_policy: "unkown",
    border_policy_link: "",
    comment_en: "",
    comment_nl: "",
    start: "",
    end: "",
    link: "",
    link2: "",
    new_death_daily_delta_percent: "",
    new_death_daily_delta_absolute: ""
  },
  {
    country: "FI",
    name_worldometers: "Finland",
    name_en: "Finland",
    name_nl: "Finland",
    lockdown: "no",
    impact_daily_life: "unkown",
    impact_daily_life_link: "",
    freedom_of_movement: "unkown",
    freedom_of_movement_link: "",
    border_policy: "unkown",
    border_policy_link: "",
    comment_en: "Emergency laws in place",
    comment_nl: "Noodplannen liggen klaar",
    start: "",
    end: "",
    link: "",
    link2: "",
    new_death_daily_delta_percent: "",
    new_death_daily_delta_absolute: ""
  },
  {
    country: "FR",
    name_worldometers: "France",
    name_en: "France",
    name_nl: "Frankrijk",
    lockdown: "yes",
    impact_daily_life: "5. all non-essential shops closed",
    impact_daily_life_link: "",
    freedom_of_movement: "2. light restrictions",
    freedom_of_movement_link: "",
    border_policy: "unkown",
    border_policy_link: "",
    comment_en: "Need to carry form stating reason for leaving house",
    comment_nl:
      "Je hebt formulier nodig om aan te tonen waarom je op straat bent.",
    start: "Mar 16, 2020",
    end: "",
    link:
      "https://www.businessinsider.com/coronavirus-france-requires-form-leave-house-walk-shopping-2020-3?r=US&IR=T",
    link2: "",
    new_death_daily_delta_percent: "",
    new_death_daily_delta_absolute: ""
  },
  {
    country: "DE",
    name_worldometers: "Germany",
    name_en: "Germany",
    name_nl: "Duitsland",
    lockdown: "yes",
    impact_daily_life: "5. all non-essential shops closed",
    impact_daily_life_link: "",
    freedom_of_movement: "3. strong restrictions",
    freedom_of_movement_link: "",
    border_policy: "5. closed all borders and air travel",
    border_policy_link:
      "https://www.aljazeera.com/news/2020/03/coronavirus-travel-restrictions-border-shutdowns-country-200318091505922.html",
    comment_en: "",
    comment_nl: "",
    start: "",
    end: "",
    link:
      "https://www.theguardian.com/world/2020/mar/18/coronavirus-lockdown-eu-belgium-germany-adopt-measures",
    link2:
      "https://uk.reuters.com/article/us-health-coronavirus-germany-economy/merkel-says-lets-get-through-this-as-shops-bars-and-churches-shut-idUKKBN213178",
    new_death_daily_delta_percent: "-39%",
    new_death_daily_delta_absolute: -14
  },
  {
    country: "GB",
    name_worldometers: "UK",
    name_en: "Great-Britain",
    name_nl: "Groot-Brittannië",
    lockdown: "yes",
    impact_daily_life: "5. all non-essential shops closed",
    impact_daily_life_link:
      "https://www.cnbc.com/2020/03/20/coronavirus-uk-pm-announces-lockdown-measures-in-london.html",
    freedom_of_movement: "3. strong restrictions",
    freedom_of_movement_link:
      "https://www.nhs.uk/conditions/coronavirus-covid-19/self-isolation-advice/",
    border_policy: "unkown",
    border_policy_link: "",
    comment_en:
      "Cafes, Pubs and Restaurants closed (except for take-out food). Nightclubs, Theatres, Cinemas, Gyms and Leisure centres to close as soon as possible.",
    comment_nl: "",
    start: "Mar 20, 2020",
    end: "",
    link: "https://www.bbc.co.uk/news/uk-51981653",
    link2: "",
    new_death_daily_delta_percent: "-87%",
    new_death_daily_delta_absolute: -76
  },
  {
    country: "GR",
    name_worldometers: "Greece",
    name_en: "Greece",
    name_nl: "Griekenland",
    lockdown: "yes",
    impact_daily_life: "unkown",
    impact_daily_life_link: "",
    freedom_of_movement: "unkown",
    freedom_of_movement_link: "",
    border_policy: "unkown",
    border_policy_link: "",
    comment_en: "",
    comment_nl: "",
    start: "Mar 18, 2020",
    end: "",
    link:
      "https://www.tornosnews.gr/en/greek-news/society/39369-greece-in-total-lockdown-from-wednesday-due-to-coronavirus-outbreak.html",
    link2: "",
    new_death_daily_delta_percent: "",
    new_death_daily_delta_absolute: ""
  },
  {
    country: "HU",
    name_worldometers: "Hungary",
    name_en: "Hungary",
    name_nl: "Hongarije",
    lockdown: "mild",
    impact_daily_life: "unkown",
    impact_daily_life_link: "",
    freedom_of_movement: "1. no restrictions",
    freedom_of_movement_link: "",
    border_policy: "5. closed all borders and air travel",
    border_policy_link:
      "https://www.aljazeera.com/news/2020/03/coronavirus-travel-restrictions-border-shutdowns-country-200318091505922.html",
    comment_en: "Emergency laws in place",
    comment_nl: "Noodplannen liggen klaar",
    start: "Mar 13, 2020",
    end: "",
    link: "",
    link2: "",
    new_death_daily_delta_percent: "0%",
    new_death_daily_delta_absolute: 0
  },
  {
    country: "IE",
    name_worldometers: "Ireland",
    name_en: "Ireland",
    name_nl: "Ierland",
    lockdown: "mild",
    impact_daily_life: "unkown",
    impact_daily_life_link: "",
    freedom_of_movement: "2. light restrictions",
    freedom_of_movement_link: "",
    border_policy: "unkown",
    border_policy_link: "",
    comment_en: "",
    comment_nl: "",
    start: "",
    end: "",
    link: "",
    link2: "",
    new_death_daily_delta_percent: "",
    new_death_daily_delta_absolute: ""
  },
  {
    country: "IT",
    name_worldometers: "Italy",
    name_en: "Italy",
    name_nl: "Italie",
    lockdown: "yes",
    impact_daily_life: "4. take away food delivery only",
    impact_daily_life_link: "",
    freedom_of_movement: "3. strong restrictions",
    freedom_of_movement_link: "",
    border_policy: "5. closed all borders and air travel",
    border_policy_link:
      "https://www.aljazeera.com/news/2020/03/coronavirus-travel-restrictions-border-shutdowns-country-200318091505922.html",
    comment_en:
      "Under the lockdown rules, people can only leave their homes to get food or medicines (other shops are closed), or to perform other essential services or to go to work.",
    comment_nl:
      "Tijdens de lockdown mensen mogen hun huis uit voor voedsel en medicijngen (andere winkels zijn dicht) of om essentiele beroepen uit te voeren of naar werk te gaan.",
    start: "Mar 10, 2020",
    end: "Apr 3, 2020",
    link:
      "https://www.cnbc.com/2020/03/19/italys-death-rate-reaches-record-high-hospitals-in-lombardy-struggle.html",
    link2: "",
    new_death_daily_delta_percent: "",
    new_death_daily_delta_absolute: ""
  },
  {
    country: "Kosovo",
    name_worldometers: "Kosovo",
    name_en: "Kosovo",
    name_nl: "Kosovo",
    lockdown: "unkown",
    impact_daily_life: "unkown",
    impact_daily_life_link: "",
    freedom_of_movement: "unkown",
    freedom_of_movement_link: "",
    border_policy: "unkown",
    border_policy_link: "",
    comment_en: "",
    comment_nl: "",
    start: "",
    end: "",
    link: "",
    link2: "",
    new_death_daily_delta_percent: "No data available",
    new_death_daily_delta_absolute: "No data available"
  },
  {
    country: "LV",
    name_worldometers: "Latvia",
    name_en: "Latvia",
    name_nl: "Letland",
    lockdown: "unkown",
    impact_daily_life: "unkown",
    impact_daily_life_link: "",
    freedom_of_movement: "unkown",
    freedom_of_movement_link: "",
    border_policy: "5. closed all borders and air travel",
    border_policy_link:
      "https://www.aljazeera.com/news/2020/03/coronavirus-travel-restrictions-border-shutdowns-country-200318091505922.html",
    comment_en: "",
    comment_nl: "",
    start: "",
    end: "",
    link: "",
    link2: "",
    new_death_daily_delta_percent: "",
    new_death_daily_delta_absolute: ""
  },
  {
    country: "LT",
    name_worldometers: "Lithuania",
    name_en: "Lithuania",
    name_nl: "Litouwen",
    lockdown: "unkown",
    impact_daily_life: "unkown",
    impact_daily_life_link: "",
    freedom_of_movement: "unkown",
    freedom_of_movement_link: "",
    border_policy: "4. closed some borders and air travel",
    border_policy_link:
      "https://www.aljazeera.com/news/2020/03/coronavirus-travel-restrictions-border-shutdowns-country-200318091505922.html",
    comment_en: "",
    comment_nl: "",
    start: "",
    end: "",
    link: "",
    link2: "",
    new_death_daily_delta_percent: "100%",
    new_death_daily_delta_absolute: 1
  },
  {
    country: "LU",
    name_worldometers: "Luxembourg",
    name_en: "Luxembourg",
    name_nl: "Luxemburg",
    lockdown: "yes",
    impact_daily_life: "5. all non-essential shops closed",
    impact_daily_life_link:
      "https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_Luxembourg",
    freedom_of_movement: "3. strong restrictions",
    freedom_of_movement_link:
      "https://today.rtl.lu/news/luxembourg/a/1483941.html",
    border_policy: "4. closed some borders and air travel",
    border_policy_link:
      "https://luxtimes.lu/luxembourg/40100-germany-border-checks-add-to-luxembourg-virus-lockdown",
    comment_en: "",
    comment_nl: "",
    start: "",
    end: "",
    link: "",
    link2: "",
    new_death_daily_delta_percent: "",
    new_death_daily_delta_absolute: ""
  },
  {
    country: "MT",
    name_worldometers: "Malta",
    name_en: "Malta",
    name_nl: "Malta",
    lockdown: "unkown",
    impact_daily_life: "unkown",
    impact_daily_life_link: "",
    freedom_of_movement: "unkown",
    freedom_of_movement_link: "",
    border_policy: "unkown",
    border_policy_link: "",
    comment_en: "",
    comment_nl: "",
    start: "",
    end: "",
    link: "",
    link2: "",
    new_death_daily_delta_percent: "",
    new_death_daily_delta_absolute: ""
  },
  {
    country: "NO",
    name_worldometers: "Norway",
    name_en: "Norway",
    name_nl: "Norwegen",
    lockdown: "no",
    impact_daily_life: "unkown",
    impact_daily_life_link: "",
    freedom_of_movement: "unkown",
    freedom_of_movement_link: "",
    border_policy: "4. closed some borders and air travel",
    border_policy_link: "",
    comment_en:
      "Norway is locked down too. $2000 fine or 15days in jail for rule violation. People not allowed to go in their 2nd house",
    comment_nl:
      "$2000 boete of 15 dagen in de cel bij overtreding. Mensen mogen niet naar hun tweede huis.",
    start: "",
    end: "",
    link:
      "https://www.fhi.no/en/op/novel-coronavirus-facts-advice/facts-and-general-advice/advice-and-information-to-public/",
    link2: "",
    new_death_daily_delta_percent: "0%",
    new_death_daily_delta_absolute: 0
  },
  {
    country: "PL",
    name_worldometers: "Poland",
    name_en: "Poland",
    name_nl: "Polen",
    lockdown: "mild",
    impact_daily_life: "4. take away food delivery only",
    impact_daily_life_link: "",
    freedom_of_movement: "2. light restrictions",
    freedom_of_movement_link: "",
    border_policy: "5. closed all borders and air travel",
    border_policy_link: "",
    comment_en:
      "Bars, restaurants, shopping centres and borders closed and all flights are cancelled",
    comment_nl:
      "Restaurants, cafes en winkelcentra gesloten. Alle vluchten geannuleerd.",
    start: "Mar 13, 2020",
    end: "",
    link:
      "https://www.thefirstnews.com/article/poland-in-covid-19-lockdown-pm-orders-bars-restaurants-shopping-centres-and-borders-closed---and-cancels-all-flights-11142",
    link2: "",
    new_death_daily_delta_percent: "50%",
    new_death_daily_delta_absolute: 1
  },
  {
    country: "PT",
    name_worldometers: "Portugal",
    name_en: "Portugal",
    name_nl: "Portugal",
    lockdown: "yes",
    impact_daily_life: "unkown",
    impact_daily_life_link: "",
    freedom_of_movement: "unkown",
    freedom_of_movement_link: "",
    border_policy: "5. closed all borders and air travel",
    border_policy_link:
      "https://www.aljazeera.com/news/2020/03/coronavirus-travel-restrictions-border-shutdowns-country-200318091505922.html",
    comment_en: "",
    comment_nl: "",
    start: "",
    end: "",
    link:
      "https://www.euractiv.com/section/politics/news/portuguese-president-on-lockdown-as-coronavirus-spreads-across-eu/",
    link2: "",
    new_death_daily_delta_percent: "0%",
    new_death_daily_delta_absolute: 0
  },
  {
    country: "RO",
    name_worldometers: "Romania",
    name_en: "Romania",
    name_nl: "Roemenië",
    lockdown: "unkown",
    impact_daily_life: "unkown",
    impact_daily_life_link: "",
    freedom_of_movement: "unkown",
    freedom_of_movement_link: "",
    border_policy: "unkown",
    border_policy_link: "",
    comment_en: "",
    comment_nl: "",
    start: "",
    end: "",
    link: "",
    link2: "",
    new_death_daily_delta_percent: "-80%",
    new_death_daily_delta_absolute: -4
  },
  {
    country: "RS",
    name_worldometers: "Serbia",
    name_en: "Serbia",
    name_nl: "Servië",
    lockdown: "mild",
    impact_daily_life: "unkown",
    impact_daily_life_link: "",
    freedom_of_movement: "unkown",
    freedom_of_movement_link: "",
    border_policy: "5. closed all borders and air travel",
    border_policy_link:
      "https://www.aljazeera.com/news/2020/03/coronavirus-travel-restrictions-border-shutdowns-country-200318091505922.html",
    comment_en: "Emergency laws in place. Possible border lockdown",
    comment_nl: "Noodplannen liggen klaar. Grenzen gaan mogelijk dicht.",
    start: "Mar 15, 2020",
    end: "",
    link: "",
    link2: "",
    new_death_daily_delta_percent: "",
    new_death_daily_delta_absolute: ""
  },
  {
    country: "SK",
    name_worldometers: "Slovakia",
    name_en: "Slovakia",
    name_nl: "Slowakije",
    lockdown: "mild",
    impact_daily_life: "4. take away food delivery only",
    impact_daily_life_link: "",
    freedom_of_movement: "2. light restrictions",
    freedom_of_movement_link: "",
    border_policy: "4. closed some borders and air travel",
    border_policy_link: "",
    comment_en: "",
    comment_nl: "",
    start: "Mar 16, 2020",
    end: "",
    link: "https://korona.gov.sk",
    link2: "",
    new_death_daily_delta_percent: "",
    new_death_daily_delta_absolute: ""
  },
  {
    country: "SI",
    name_worldometers: "Slovenia",
    name_en: "Slovenia",
    name_nl: "Slovenië",
    lockdown: "yes",
    impact_daily_life: "5. all non-essential shops closed",
    impact_daily_life_link: "",
    freedom_of_movement: "2. light restrictions",
    freedom_of_movement_link:
      "https://english.sta.si/2742506/slovenia-enters-lockdown-mode",
    border_policy: "4. closed some borders and air travel",
    border_policy_link:
      "https://www.reuters.com/article/us-health-coronavirus-slovenia-italy-idUSKBN20X2LU",
    comment_en:
      "All non-essentials shops are closed. Majority of border crossings are closed, the ones that remain open have tight border checks. People are allowed to go out, but only individually or with people from their household or with coworkers. Groups of more than 5 people are not allowed. Fines up to 400€ for an individuals breaking this are in place. People aged 65+ years must work from home.",
    comment_nl: "",
    start: "Mar 20, 2020",
    end: "",
    link: "https://www.gov.si/en/topics/coronavirus-disease-covid-19/",
    link2: "",
    new_death_daily_delta_percent: "0%",
    new_death_daily_delta_absolute: 0
  },
  {
    country: "ES",
    name_worldometers: "Spain",
    name_en: "Spain",
    name_nl: "Spanje",
    lockdown: "yes",
    impact_daily_life: "4. take away food delivery only",
    impact_daily_life_link: "",
    freedom_of_movement: "3. strong restrictions",
    freedom_of_movement_link: "",
    border_policy: "5. closed all borders and air travel",
    border_policy_link:
      "https://www.aljazeera.com/news/2020/03/coronavirus-travel-restrictions-border-shutdowns-country-200318091505922.html",
    comment_en: "",
    comment_nl: "",
    start: "Mar 14, 2020",
    end: "",
    link:
      "https://www.theguardian.com/world/2020/mar/15/spain-city-streets-turn-quiet-coronavirus-lockdown-madrid-barcelona",
    link2: "",
    new_death_daily_delta_percent: "-35%",
    new_death_daily_delta_absolute: -237
  },
  {
    country: "SE",
    name_worldometers: "Sweden",
    name_en: "Sweden",
    name_nl: "Zweden",
    lockdown: "unkown",
    impact_daily_life: "1. nothing closed",
    impact_daily_life_link: "",
    freedom_of_movement: "2. light restrictions",
    freedom_of_movement_link:
      "https://www.thelocal.se/20200310/timeline-how-the-coronavirus-has-developed-in-sweden",
    border_policy: "1. no restrictions",
    border_policy_link:
      "https://www.thelocal.se/20200310/timeline-how-the-coronavirus-has-developed-in-sweden",
    comment_en: "",
    comment_nl: "",
    start: "",
    end: "",
    link: "",
    link2: "",
    new_death_daily_delta_percent: "-69%",
    new_death_daily_delta_absolute: -9
  },
  {
    country: "CH",
    name_worldometers: "Switzerland",
    name_en: "Switzerland",
    name_nl: "Zwitserland",
    lockdown: "yes",
    impact_daily_life: "5. all non-essential shops closed",
    impact_daily_life_link: "",
    freedom_of_movement: "2. light restrictions",
    freedom_of_movement_link: "",
    border_policy: "5. closed all borders and air travel",
    border_policy_link:
      "https://www.aljazeera.com/news/2020/03/coronavirus-travel-restrictions-border-shutdowns-country-200318091505922.html",
    comment_en:
      "Restaurants, bars, non essential business closed. Borders checks in place.",
    comment_nl:
      "Restaurants, barren en niet kritieke winkels zijn gesloten. Grenscontrole van kracht.",
    start: "Mar 16, 2020",
    end: "Apr 19, 2020",
    link:
      "https://www.swissinfo.ch/eng/covid-19_switzerland-declares-coronavirus-crisis-an--extraordinary--situation/45620148",
    link2:
      "https://www.bag.admin.ch/bag/en/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov/situation-schweiz-und-international.html",
    new_death_daily_delta_percent: "1250%",
    new_death_daily_delta_absolute: 25
  },
  {
    country: "NL",
    name_worldometers: "Netherlands",
    name_en: "Netherlands",
    name_nl: "Nederland",
    lockdown: "yes",
    impact_daily_life: "4. take away food delivery only",
    impact_daily_life_link:
      "https://www.rijksoverheid.nl/actueel/nieuws/2020/03/15/aanvullende-maatregelen-onderwijs-horeca-sport",
    freedom_of_movement: "3. strong restrictions",
    freedom_of_movement_link:
      "https://www.rijksoverheid.nl/actueel/nieuws/2020/03/15/aanvullende-maatregelen-onderwijs-horeca-sport",
    border_policy: "2. light restrictions",
    border_policy_link:
      "https://www.aljazeera.com/news/2020/03/coronavirus-travel-restrictions-border-shutdowns-country-200318091505922.html",
    comment_en:
      "Lockdown of schools, bars, events. People are allowed to go to work.",
    comment_nl:
      "Alle bijeenkomsten zijn tot 1 juni verboden, ook die met minder dan honderd mensen. Verder gaat de politie boetes uitdelen als mensen zich in de buitenlucht of in winkels niet aan de regel houden om minstens 1,5 meter afstand te houden.",
    start: "",
    end: "",
    link:
      "https://nos.nl/artikel/2328121-coronanieuws-23-maart-kabinet-verstevigt-coronamaatregelen.html",
    link2: "",
    new_death_daily_delta_percent: "27%",
    new_death_daily_delta_absolute: 17
  }
];
